# Generated by Django 2.1.7 on 2019-10-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20191017_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackprofile',
            name='HashtagToFeedback',
            field=models.CharField(default='before', max_length=100),
        ),
        migrations.AddField(
            model_name='hashtagprofile',
            name='FeedbackToHashtag',
            field=models.CharField(default='before', max_length=300),
        ),
    ]
