# Generated by Django 2.2.5 on 2019-10-23 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20191018_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackprofile',
            name='Rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
